name: flutter_aws_s3_client
description: A simple, unofficial AWS S3 client in dart. Supports downloading objects and listing objects in a bucket.
version: 0.6.0
homepage: https://github.com/diagnosia/flutter_aws_s3_client
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  amazon_cognito_identity_dart_2: ^3.7.0
  built_value: "^8.0.0"
  built_collection: "^5.0.0"
  xml2json : ^5.0.0
  http: ^1.2.2
dev_dependencies:
  built_value_generator: "^8.0.0"
  build_runner: ^2.4.6
